baseURL = "https://saisyam.com/"
languageCode = "en-us"
title = "Saisyam - My Blog"
theme = "blog"
paginate = 5
canonifyurls = true
disqusShortname = "saisyam-1"
googleAnalytics = "UA-50423294-1"
enableRobotsTXT = true
enableEmoji = true
publishDir = "docs"

[params]
author = "Saisyam"
logo = "images/profile.jpg"
header = "Saisyam - Personal Blog"

facebook = "saisyam.dampuri.5667"
twitter = "saisyam1"
instagram = "saisyamdampuri"
github = "saisyam"
linkedin = "saisyam"

[permalinks]
  "/posts" = "/:title/"

[markup.goldmark.renderer]
unsafe= true
