baseURL = "https://saisyam.com/"
languageCode = "en-us"
title = "Saisyam Personal Website"
theme = "pure"
paginate = 10
canonifyurls = true
disqusShortname = "saisyam-1"
googleAnalytics = "UA-504232"
enableRobotsTXT = true
enableEmoji = true
#pygmentsCodefences = true
#pygmentsStyle = "pygments"

[params]
author = "Saisyam"
logo = "images/profile.jpg"
header = "Saisyam - Personal Blog"

facebook = "saisyam.dampuri.5667"
twitter = "saisyam1"
instagram = "saisyamdampuri"
github = "saisyam"
linkedin = "saisyam"

[permalinks]
  "/posts" = "/:title/"

[markup.goldmark.renderer]
unsafe= true